/**
 * Display names for bundled theme ids. Extracted from panel.js so both
 * panel.js and the sections/*.js mixins can use it without a circular
 * require (mixins are required BY panel.js to be attached to its
 * prototype, so they can't safely require panel.js back).
 */
const THEME_LABELS = {
  "betterclaude-default": "BetterClaude Default",
  "midnight-violet": "Midnight Violet",
  "ocean-abyss": "Ocean Abyss",
  "rose-glass": "Rose Glass",
  "hacker-green": "Hacker Green",
  "warm-dusk": "Warm Dusk",
  "nord": "Nord",
  "catppuccin-mocha": "Catppuccin Mocha",
  "tokyo-night": "Tokyo Night",
  "dracula": "Dracula",
  "solarized-light": "Solarized Light",
  "high-contrast": "High Contrast",
  "gruvbox-dark": "Gruvbox Dark",
  "one-dark": "One Dark",
  "cyberpunk-neon": "Cyberpunk Neon",
  "forest-light": "Forest Light",
  "sakura-blossom": "Sakura Blossom",
  "vaporwave": "Vaporwave",
  "arctic-light": "Arctic Light",
  "monokai": "Monokai",
  "aurora-ink": "Aurora Ink",
  "porcelain": "Porcelain",
  "graphite": "Graphite",
  "solar-dusk": "Solar Dusk",
  "sage-paper": "Sage Paper",
  "crimson-night": "Crimson Night",
  "arctic-glass": "Arctic Glass",
  "sepia-study": "Sepia Study",
  "neon-terminal": "Neon Terminal",
  "oceanic": "Oceanic",
  "clay": "Clay",
  "lavender-mist": "Lavender Mist",
  "midnight-copper": "Midnight Copper",
  "pearl": "Pearl",
  "forest-floor": "Forest Floor",
  "high-contrast-dark": "High Contrast Dark",
  "high-contrast-light": "High Contrast Light",
  "rose-quartz": "Rose Quartz",
  "ember": "Ember",
  "deep-sea": "Deep Sea",
  "mint-frost": "Mint Frost",
  "blueprint": "Blueprint",
  "walnut": "Walnut",
  "slate-mono": "Slate Mono",
  "cream-soda": "Cream Soda",
  "electric-lime": "Electric Lime",
  "quiet-sand": "Quiet Sand",
  "iceberg": "Iceberg",
  "plum-velvet": "Plum Velvet",
  "tangerine": "Tangerine",
  "raincloud": "Raincloud",
  "matcha": "Matcha",
  "mono-white": "Mono White",
  "mono-black": "Mono Black",
  "orchid": "Orchid",
  "cobalt": "Cobalt",
  "cherry-cola": "Cherry Cola",
  "stone": "Stone",
  "honeycomb": "Honeycomb",
  "glacier": "Glacier",
  "cyberpunk": "Cyberpunk",
  "newspaper": "Newspaper",
  "coffee-house": "Coffee House",
  "synthwave": "Synthwave",
  "nordic": "Nordic",
  "moss": "Moss",
  "candy": "Candy",
  "volcanic": "Volcanic",
  "denim": "Denim",
  "pistachio": "Pistachio",
  "infrared": "Infrared",
  "night-owl": "Night Owl",
  "linen": "Linen",
  "aubergine": "Aubergine",
  "zinc": "Zinc",
  "coral-reef": "Coral Reef",
  "vapor": "Vapor",
  "bamboo": "Bamboo",
  "obsidian": "Obsidian",
  // Konami-unlocked bonus theme — kept out of the visible grid until then
  // (see panel.js _renderThemes), so the label doubles as a small reveal.
  "secret-rainbow": "Secret Rainbow",
};

module.exports = { THEME_LABELS };
